# Simulation Data

In [2]:
import pandas as pd

In [3]:
STR = "n1000_m5_size100_cov0.1_p5_s0"

df_read_counts = pd.read_parquet(f"../data/simulation/ground_truth_with_loss/{STR}/sim_read_count.parquet")
df_read_counts

,m0,m1,m2,m3,m4,m5,m6,m7,m8,m9,...,m451,m452,m453,m454,m455,m456,m457,m458,m459,m460
s0,0,0,0,0,0,0,0,1,0,0,...,0,0,0,0,0,0,0,0,0,0
s1,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
s2,0,0,0,0,0,0,0,0,0,1,...,0,0,0,0,0,0,0,0,1,0
s3,0,0,0,1,1,0,0,0,0,0,...,0,0,1,0,0,0,0,0,1,0
s4,0,0,0,0,0,0,0,1,0,0,...,0,0,1,0,1,0,1,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
s995,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,1,0
s996,0,0,0,0,0,0,0,0,0,0,...,0,0,1,0,1,1,0,0,0,0
s997,0,0,0,0,0,0,0,0,1,0,...,0,0,0,0,0,0,0,0,0,0
s998,0,0,0,0,0,0,0,0,1,0,...,0,0,0,0,1,0,0,0,1,1
s999,1,0,0,0,0,0,0,1,0,0,...,0,0,0,0,0,0,0,0,0,0

In [4]:
df_total_long = df_read_counts.reset_index().melt(id_vars='index', var_name='mutation', value_name='total')
df_total_long = df_total_long.rename(columns={'index': 'cell_id'})
df_total_long

       cell_id mutation  total
0           s0       m0      0
1           s1       m0      0
2           s2       m0      0
3           s3       m0      0
4           s4       m0      0
...        ...      ...    ...
460995    s995     m460      0
460996    s996     m460      0
460997    s997     m460      0
460998    s998     m460      1
460999    s999     m460      0

[461000 rows x 3 columns]

In [5]:
df_variant_counts = pd.read_parquet(f"../data/simulation/ground_truth_with_loss/{STR}/sim_variant_count.parquet")
df_variant_counts

,m0,m1,m2,m3,m4,m5,m6,m7,m8,m9,...,m451,m452,m453,m454,m455,m456,m457,m458,m459,m460
s0,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
s1,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
s2,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
s3,0,0,0,0,1,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
s4,0,0,0,0,0,0,0,1,0,0,...,0,0,1,0,1,0,1,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
s995,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,1,0
s996,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,1,0,0,0,0,0
s997,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
s998,0,0,0,0,0,0,0,0,1,0,...,0,0,0,0,1,0,0,0,0,1
s999,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0

In [6]:
df_var_long = df_variant_counts.reset_index().melt(id_vars='index', var_name='mutation', value_name='variant')
df_var_long = df_var_long.rename(columns={'index': 'cell_id'})
df_var_long

       cell_id mutation  variant
0           s0       m0        0
1           s1       m0        0
2           s2       m0        0
3           s3       m0        0
4           s4       m0        0
...        ...      ...      ...
460995    s995     m460        0
460996    s996     m460        0
460997    s997     m460        0
460998    s998     m460        1
460999    s999     m460        0

[461000 rows x 3 columns]

In [7]:
df_long = pd.merge(df_total_long, df_var_long, on=['cell_id', 'mutation'])
df_long

       cell_id mutation  total  variant
0           s0       m0      0        0
1           s1       m0      0        0
2           s2       m0      0        0
3           s3       m0      0        0
4           s4       m0      0        0
...        ...      ...    ...      ...
460995    s995     m460      0        0
460996    s996     m460      0        0
460997    s997     m460      0        0
460998    s998     m460      1        1
460999    s999     m460      0        0

[461000 rows x 4 columns]

In [8]:
df_long = df_long[df_long['total'] != 0]
df_long['cell_id'] = df_long['cell_id'].str[1:].astype(int)
df_long['mutation'] = df_long['mutation'].str[1:].astype(int)

df_long

/var/folders/nz/jn74t1g51q10qyclfkkr8cgm0000gq/T/ipykernel_9354/2392763685.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_long['cell_id'] = df_long['cell_id'].str[1:].astype(int)
/var/folders/nz/jn74t1g51q10qyclfkkr8cgm0000gq/T/ipykernel_9354/2392763685.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_long['mutation'] = df_long['mutation'].str[1:].astype(int)

        cell_id  mutation  total  variant
10           10         0      1        0
33           33         0      1        0
44           44         0      1        0
78           78         0      1        0
79           79         0      1        0
...         ...       ...    ...      ...
460976      976       460      1        0
460979      979       460      1        0
460985      985       460      1        0
460992      992       460      1        0
460998      998       460      1        1

[44035 rows x 4 columns]

In [9]:
df_mut_bin = pd.read_parquet(f"../data/simulation/ground_truth_with_loss/{STR}/sim_mutation_to_bin_mapping.parquet")
df_mut_bin.index.name = "mutation"

df_mut_bin

          bin
mutation
0           9
1           2
2           9
3           4
4           9
...       ...
456         7
457         9
458         0
459         7
460         1

[461 rows x 1 columns]

In [10]:
import numpy as np

In [11]:
df_mut_bin_unq = df_mut_bin.drop_duplicates(subset=["bin"], keep="first")
df_mut_bin_unq

          bin
mutation
0           9
1           2
3           4
5           1
6           3
10          7
21          6
26          0
27          8
31          5

In [12]:
df_mut_bin_unq['bin_id'] = np.arange(len(df_mut_bin_unq))
df_mut_bin_unq

/var/folders/nz/jn74t1g51q10qyclfkkr8cgm0000gq/T/ipykernel_9354/3230863571.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_mut_bin_unq['bin_id'] = np.arange(len(df_mut_bin_unq))

          bin  bin_id
mutation
0           9       0
1           2       1
3           4       2
5           1       3
6           3       4
10          7       5
21          6       6
26          0       7
27          8       8
31          5       9

In [13]:
df_mut_bin = pd.merge(df_mut_bin, df_mut_bin_unq, on='bin', how='left')
df_mut_bin.index.name = "mutation"
df_mut_bin

          bin  bin_id
mutation
0           9       0
1           2       1
2           9       0
3           4       2
4           9       0
...       ...     ...
456         7       5
457         9       0
458         0       7
459         7       5
460         1       3

[461 rows x 2 columns]

In [14]:
df_long = pd.merge(df_long, df_mut_bin, on="mutation", how='left')
df_long

       cell_id  mutation  total  variant  bin  bin_id
0           10         0      1        0    9       0
1           33         0      1        0    9       0
2           44         0      1        0    9       0
3           78         0      1        0    9       0
4           79         0      1        0    9       0
...        ...       ...    ...      ...  ...     ...
44030      976       460      1        0    1       3
44031      979       460      1        0    1       3
44032      985       460      1        0    1       3
44033      992       460      1        0    1       3
44034      998       460      1        1    1       3

[44035 rows x 6 columns]

In [15]:
import os

os.makedirs(f"../data/simulation/pharming_input/{STR}", exist_ok=True)

In [16]:
pharming_read_counts = pd.DataFrame({
    'segment': df_long['bin_id'],
    'mutation': df_long['mutation'],
    'cell': df_long['cell_id'],
    'varReads': df_long['variant'],
    'totReads': df_long['total'],
})
pharming_read_counts.to_csv(f"../data/simulation/pharming_input/{STR}/read_counts.tsv", index=False, sep='\t')
pharming_read_counts

       segment  mutation  cell  varReads  totReads
0            0         0    10         0         1
1            0         0    33         0         1
2            0         0    44         0         1
3            0         0    78         0         1
4            0         0    79         0         1
...        ...       ...   ...       ...       ...
44030        3       460   976         0         1
44031        3       460   979         0         1
44032        3       460   985         0         1
44033        3       460   992         0         1
44034        3       460   998         1         1

[44035 rows x 5 columns]

In [17]:
df_copy_numbers_bins = pd.read_parquet(f"../data/simulation/ground_truth_with_loss/{STR}/sim_copy_numbers_of_segments.parquet")
df_copy_numbers_bins

   0  1  2  3  4  5  6  7  8  9
0  5  2  5  4  4  2  5  4  3  2
1  5  2  4  3  4  1  5  3  2  2
2  5  2  3  3  4  1  5  3  2  2
3  4  2  4  3  3  1  4  3  2  2
4  3  2  3  3  3  1  4  2  2  2

In [30]:
df_copy_numbers = pd.read_parquet(
    f"../data/simulation/ground_truth_with_loss/{STR}/sim_copy_numbers.parquet"
)

df_copy_numbers.index = df_copy_numbers.index.str[1:].astype(int)
df_copy_numbers.columns = df_copy_numbers.columns.str[1:].astype(int)

# long format
df_copy_numbers_long = (
    df_copy_numbers
    .reset_index()
    .melt(id_vars="index", var_name="mutation", value_name="copy")
    .rename(columns={"index": "cell"})
)

# attach bin id
df_copy_numbers_long_cn = df_copy_numbers_long.merge(
    df_mut_bin.reset_index()[["mutation", "bin_id"]],
    on="mutation",
    how="left"
)

# ---- KEY FIX: aggregate per cell / segment ----
df_segment_cn = (
    df_copy_numbers_long_cn
    .groupby(["cell", "bin_id"], as_index=False)["copy"]
    .mean()   # or max / first depending on your model
)

pharming_copy_numbers = pd.DataFrame({
    "segment": df_segment_cn["bin_id"],
    "cell": df_segment_cn["cell"],
    "copiesX": df_segment_cn["copy"],
    "copiesY": 0
})

# sanity check
assert not pharming_copy_numbers.duplicated(["cell", "segment"]).any()

pharming_copy_numbers.to_csv(
    f"../data/simulation/pharming_input/{STR}/copy_numbers.csv",
    index=False
)

In [31]:
pharming_copy_numbers.groupby(["cell","segment"]).size().sort_values(ascending=False).head()

cell  segment
0     0          1
667   0          1
666   3          1
      4          1
      5          1
dtype: int64

In [19]:
# df_copy_numbers = df_copy_numbers.loc[:, df_mut_bin_unq.index]
# df_copy_numbers

In [20]:
# df_copy_numbers_long_cn = pd.merge(df_copy_numbers_long, df_mut_bin_unq, on='mutation', how='left')
# df_copy_numbers_long_cn

In [21]:
pharming_copy_numbers.isna().any().any()

np.False_

In [22]:
unique_segments = df_mut_bin_unq['bin_id'].unique()
unique_segments = sorted(unique_segments)

with open(f"../data/simulation/pharming_input/{STR}/segments.txt", "w") as f:
    for seg in unique_segments:
        f.write(f"{seg}\n")

print("✅ Saved unique segment IDs to segments.txt")

✅ Saved unique segment IDs to segments.txt